### ISSUE TITLE
Remux 'colr' box as if colour_type 'nclx' is 'nclc'.

### ISSUE THREAD

**Issue by VFR-maniac** [k-takata/mp3infp#5]
'colr' is defined in both ISO Base Media and QuickTime file format.
However, for ISO 'colr', 'nclx' is defined, and for QuickTime, 'nclc' is defined instead.
'nclx' has additional one byte field to 'nclc'.
And, mp3infp or mp4v2 remux 'colr' box as if colour_type 'nclx' is 'nclc'.
This makes 'colr' box broken.

**Comment by k-takata** [comment]
I hope this is fixed with v2.55 beta3.
